### ISSUE TITLE
请问可否将顶栏设置为常驻？

### ISSUE THREAD

**Issue by zzz51522** [mustakshif/Hadeeth-for-SiYuan#3]
目前主题顶栏为鼠标触发显示，请问是否有考虑将顶栏常驻作为可选项？

因为一些常用插件按钮位于顶栏，目前鼠标触发显示增加了使用插件的步骤（鼠标移至顶栏→等待顶栏显示→点击插件按钮）。而常驻顶栏可以直接点击到插件按钮。

Savor主题中提供了这种选项，可以作为参考。望考虑~

![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/145221733/1cf509b4-6a04-4c84-ab6e-2f040bf9ae91)

**Comment by mustakshif** [comment]
谢谢你的建议！

我也考虑过这个问题，最近的更新中给出的解决方案是扩大顶栏图标的点击响应区域，顶栏一弹出，鼠标不用多余的运动就可以点击到图标。所以如果平时有常用的插件，可以直接移动鼠标到顶栏大致位置，顶栏弹出时直接点击一下就行。

不知这样能否解决你的问题？我会再看看是否有更多人反馈这个需求，后续可能会加上的。

**Comment by zzz51522** [comment]
如果目前没有上线常驻顶栏计划，这样也可以先顶着，毕竟常用的插件大概位置还是比较熟悉的。

顶栏常驻的方案再收集收集需求吧。我看主题介绍是以简洁为主打点，并且卖点之一就是通过隐藏顶栏以换取更多空间。这也算是Hadeeth的特色了。再收集一些需求，尽量在简洁性和易用性之间取得平衡。

另外，不知道您是否加了思源QQ群，我在群里看到有两个群友对于隐藏顶栏有些不适应。所以常驻顶栏的需求建议持续关注下。
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/145221733/69ecce7c-17b8-4591-b35e-e21601d9e465)
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/145221733/229b9c51-6c5d-4c94-bcb5-fee37b7c6bb2)

**Comment by mustakshif** [comment]
感谢你提供的信息！我在二群哈哈，之前在论坛好像看到不太建议一个人加多群所以我就没加。

Windows上我只在虚拟机测试过，基本上能弹出，但可能Windows窗口边缘用于调整大小的区域比Mac大一点所以更难触发顶栏。

这样的话，看来确实影响使用了，我会在后续更新解决这个问题的。

**Comment by mustakshif** [comment]
新版本已支持常驻顶栏，请更新后查看主题说明～

**Comment by zzz51522** [comment]
效率很高呀~赞！
