### ISSUE TITLE
闪卡样式的想法

### ISSUE THREAD

**Issue by zzz51522** [mustakshif/Hadeeth-for-SiYuan#4]
看到更新计划中有优化闪卡样式的规划，提一个需求，作为优化时的参考。

问题：思源笔记以文档作为闪卡时，闪卡复习页面不显示文档名。
需求想法：
1.在闪卡复习页面展示文档名。因为不懂技术，所以这一点我不知道是否可以通过主题实现，如果可以实现最好。
2.如1无法实现，可以考虑强化显示面包屑中的文档名。
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/145221733/c5755309-d2c7-4664-92f6-d574d511e147)

**Comment by mustakshif** [comment]
第一点我觉得可以去思源官方论坛或 Github 提一下看看，比如说在闪卡对话框标题中显示文档名；

第二点可以操作，但是也得等思源调整闪卡这一块的页面结构后才比较好弄😂。但是如果要强调前面一整段文字的话是比较好弄的：
![screenshot](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/100056458/f307f360-5ced-4dfb-a383-086033347b1a)

如果这个可以接受，我可以给你解决方法。

总之这个需求我先 mark，看后续官方是否会优化吧

**Comment by zzz51522** [comment]
向官方提需求和等待思源调整闪卡页面结构，看起来需要的时间比较长🤦‍♂️

> 如果强调整段可以接受，我可以给你解决方法。

请问这个解决方案是什么，辛苦透露一下，hhhh

**Comment by mustakshif** [comment]
可以去 `设置 - 外观 - 代码片段` ，在 CSS 选项卡中新增以下代码并启用：

```
.card__main .protyle-breadcrumb__bar>.protyle-breadcrumb__item:first-child .protyle-breadcrumb__text {
    font-weight: bold; /* 字体加粗 */
    color: var(--b3-theme-primary); /* 字体颜色改为主题色 */
}
```
