### ISSUE TITLE
可否提供选项，让上方的菜单栏不隐藏？

### ISSUE THREAD

**Issue by wujiahao15** [mustakshif/Hadeeth-for-SiYuan#5]
在 macOS 系统下，全屏显示时，会和系统的界面干扰触发。

<img width="351" alt="image" src="https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/22017865/70280002-20cf-456e-ba90-4fa3a7d23d6d">

**Comment by wujiahao15** [comment]
看了下 README，有提到这个问题。

<img width="799" alt="image" src="https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/22017865/88a5ab12-096e-42f0-b5d0-c737e4ef0471">

**Comment by mustakshif** [comment]
谢谢反馈，我还没注意过这个问题。下个版本将支持全屏自动钉住顶栏，避免频繁手动开闭
