### ISSUE TITLE
“/”菜单建议增加类似savor主题弹出的菜单形式

### ISSUE THREAD

**Issue by xy0124** [mustakshif/Hadeeth-for-SiYuan#6]
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/99000021/77987704-dffa-4440-9e13-ced927430821)
如图所示，为了是操作更加直观。

**Comment by mustakshif** [comment]
好的，谢谢反馈。会纳入开发计划

**Comment by mustakshif** [comment]
多栏布局的 `/` 菜单已在下个版本更新
