### ISSUE TITLE
表格默认为页面宽度

### ISSUE THREAD

**Issue by mozhux** [mustakshif/Hadeeth-for-SiYuan#7]
如题，希望表格能默认为页面宽度，这样就能自动换行了，不然还要滚动条，比较不方便。

**Comment by mustakshif** [comment]
谢谢反馈。你说的是如果表格列太多，或者列中文本太长超出页宽后，需要横向滚动才能查看全部内容的情况吗

**Comment by mozhux** [comment]
> 谢谢反馈。你说的是如果表格列太多，或者列中文本太长超出页宽后，需要横向滚动才能查看全部内容的情况吗

是的，虽然默认也是这样，但想要savor那样的，类似于自动换行吧

**Comment by mustakshif** [comment]
好的，我抽空研究一下

**Comment by mustakshif** [comment]
平时表格用的比较少，没太在意这个不太方便的地方，感谢反馈！下个版本更新
