### ISSUE TITLE
常驻顶栏状态下的全屏切换(alt+Y)会出现按钮重叠

### ISSUE THREAD

**Issue by indevn** [mustakshif/Hadeeth-for-SiYuan#9]
**预期的效果：**（来自savor和rem craft主题）
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/11895003/d1d837b1-d1de-4d32-b306-02f62e9e8448)
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/11895003/db78873e-0c0f-403a-b119-a88ca3e4d290)

出现的问题：
常驻顶栏状态下的全屏切换(alt+Y)会出现按钮重叠，如下图所示。
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/11895003/7332f292-a8a6-4dce-9f38-eb04ff3a2806)

在默认的隐藏顶栏状态下不会出现。

**Comment by mustakshif** [comment]
收到🫡 谢谢反馈，下个版本更新
